title = "笔记管理系统"
host = "localhost"
version = "v0.1.12"
save_note_cooldown = 1

# 上传提示文本（支持占位符），{0} 为 python format 的占位符
attachment_upload_text = "共 {0} 个附件，粘贴上传或拖拽上传"

# 多行说明（保留换行和缩进）
intruction_content = """
快捷键：
    ctrl+s: 编辑笔记和保存笔记页面用于快捷保存
    ctrl+v: 笔记正文输入框用于粘贴文本和上传文件
    ctrl+o: 搜索编辑按钮并点击
    ctrl+end: 笔记正文自动滚到最下面
    end: 笔记正文中跳到当前行行尾
    ecs: 搜索退回按钮并点击

笔记详情：
    markdown 渲染模式下，点击链接，将自动打开默认浏览器
    自动增长选项指的是笔记正文侧面是否存在滚轮
"""

# 前缀导入项
prefix_import_values = [
    "【抖音】",
    "【知乎】",
    "【待办】",
    "【草稿】",
    "【Pixso AI】"
]